version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/sw-security-web-app_BE/
    overwrite: true
permissions:
  - object: /home/ec2-user/sw-security-web-app_BE/
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
