version: 0.0
os: linux

files:
  - source: /src/main/resources/application-secret.yml
    destination: /home/ec2-user/sw-security-web-app_BE/src/main/resources/application-secret.yml
permissions:
  - object: /home/ec2-user/sw-security-web-app_BE/
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
