spring:
  profiles:
    default: local

  datasource:
    url: jdbc:mysql://localhost:3306/securityInfoWeb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rlaehdus00

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: tkv0098@gmail.com
    password: avse snuo mogq fnwp
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
## Testing 환경
---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:securityInfoWeb  # H2 메모리 데이터베이스
    driver-class-name: org.h2.Driver                         # H2 드라이버
    username: sa                                             # H2 기본 사용자명
    password: 1234                                              # 비밀번호 공백

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



  h2:
    console:
      enabled: true